export class TakenReadingConnectionModel {
  constructor(
    public readonly readingId: string,
    public readonly readingDate: string,
    public readonly cadastralKey: string,
    public readonly meterNumber: string,
    public readonly address: string,
    public readonly sector: number,
    public readonly account: number,
    public readonly clientName: string,
    public readonly cardId: string,
    public readonly previousReading: number,
    public readonly currentReading: number,
    public readonly readingValue: number,
    public readonly calculatedConsumption: number,
    public readonly averageConsumption: number,
    public readonly rateName: string,
    public readonly readingTypeId: number,
    public readonly readingTypeName: string,
    public readonly novelty?: string,
    public readonly locationCapture?: { lat: number; lng: number } | null,
    public readonly locationConnection?: { lat: number; lng: number } | null,
    public readonly distanceMeters?: number | null,
    public readonly isInsideAllowedRadius?: boolean | null,
    public readonly distanceLineGeoJSON?: any | null,
    public readonly readingCode?: string | null,
    public readonly userCreatedId?: string | null,
    public readonly userCreatedName?: string | null,
    public readonly userUpdatedId?: string | null,
    public readonly userUpdatedName?: string | null,
  ) {}
}
