FROM node:24-bullseye AS deps

RUN apt-get update && apt-get install -y \
  python3 \
  make \
  g++ \
  libcairo2-dev \
  libpango1.0-dev \
  libjpeg-dev \
  libgif-dev \
  libpixman-1-dev \
  libpng-dev \
  libfreetype6-dev \
  librsvg2-dev \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3006

CMD ["npm", "run", "start:dev"]
